const upgrades = {
  'first-crochet-project': `
    <section class="pattern-card"><h2>Complete beginner practice pattern</h2><p><strong>Skill level:</strong> Beginner · <strong>Sample yarn:</strong> worsted-weight #4 · <strong>Hook:</strong> 5 mm · <strong>Finished size:</strong> about 10 × 10 cm (4 × 4 in), depending on tension.</p><h3>Gauge</h3><p>Target about 15 single crochet stitches × 16 rows = 10 cm (4 in). Gauge is a target, not a guarantee; measure your own swatch before using the size estimate.</p><h3>Abbreviations</h3><p>ch = chain · sc = single crochet · st = stitch · rep = repeat · sl st = slip stitch</p><h3>Numbered instructions</h3><ol><li>Chain 17.</li><li>Single crochet in the second chain from the hook and in each chain across: 16 sc.</li><li>Chain 1 and turn. Sc in each stitch across: 16 sc.</li><li>Repeat Row 2 until you have 15 rows of sc.</li><li>Fasten off and leave a 10–15 cm (4–6 in) tail for weaving.</li><li>Weave the tail through several stitches in two directions and trim.</li></ol><h3>Stitch-count checkpoint</h3><p>Every completed row should contain 16 sc. If the count changes, stop on that row and find the missing or extra stitch before continuing.</p><h3>Finishing and care</h3><p>Lightly shape the square flat. Wash according to the yarn label and allow it to dry flat if the yarn recommends it. This small practice piece is also useful as a future tension swatch.</p></section>`,
  'granny-square': `
    <section class="pattern-card"><h2>Classic granny square — round-by-round pattern</h2><p><strong>Sample yarn:</strong> worsted-weight #4 · <strong>Hook:</strong> 5 mm · <strong>Finished size:</strong> about 10–12 cm (4–5 in) after 4 rounds, depending on yarn and tension.</p><h3>Gauge & abbreviations</h3><p>No fixed gauge is required for a standalone square; use the same tension for every square. ch = chain · sl st = slip stitch · dc = double crochet · sp = space · rep = repeat.</p><h3>Numbered pattern</h3><ol><li>Make a magic ring or chain 4 and join. Ch 3, then work 2 dc into the center, ch 2. Repeat 3 more times. Join with a sl st to the top of the starting ch-3.</li><li>Sl st to a corner space. Ch 3, 2 dc, ch 2, 3 dc in the same corner. Ch 1. Repeat the corner sequence in each remaining corner, using ch-1 between corners. Join.</li><li>Move to a corner. Work 3 dc, ch 2, 3 dc in the corner. Ch 1. In each side space work 3 dc, ch 1. Repeat around and join.</li><li>Repeat the same corner construction. Each new round adds one 3-dc group to each side space while corners remain 3 dc, ch 2, 3 dc.</li></ol><h3>Count and shape</h3><p>Every corner must have a ch-2 space. If the square becomes a rectangle, check that every side received the same number of clusters and that no corner was accidentally treated as a side space.</p><h3>Finishing</h3><p>Block all squares to the same dimensions before joining. Weave ends securely on the back and wash according to the yarn label.</p></section>`,
  'yarn-guide': `
    <section class="pattern-card"><h2>Yarn test you can actually repeat</h2><p><strong>Recommended beginner test:</strong> smooth worsted-weight #4 yarn with a 5 mm hook. This is a starting example, not a universal yarn prescription.</p><h3>Gauge & finished fabric</h3><p>Make a 15 × 16-stitch practice swatch in single crochet. Aim for roughly 10 cm (4 in) if your project calls for that gauge. Record the yarn, hook, stitch count and measured size so you can reproduce the result.</p><h3>Numbered comparison</h3><ol><li>Choose two yarns in the same weight category.</li><li>Chain 17 and work 10 rows of sc with the same hook.</li><li>Count stitches and rows in the center area without stretching.</li><li>Compare drape, stitch definition and surface texture.</li><li>Wash a small swatch according to its care label and measure again.</li></ol><h3>Example choices</h3><p>Smooth cotton is useful for clearly defined coasters and bags. Acrylic can be practical for blankets that need easy care. Wool can provide warmth and elasticity. Always check the label and the intended use rather than choosing only by fiber name.</p><h3>Care</h3><p>Keep the yarn label until the project is finished. It contains washing and drying guidance and often the dye-lot information needed for additional skeins.</p></section>`,
  'amigurumi': `
    <section class="pattern-card"><h2>Beginner amigurumi practice ball</h2><p><strong>Sample yarn:</strong> smooth cotton or cotton-blend #3–4 · <strong>Hook:</strong> 3.5 mm · <strong>Finished size:</strong> about 6–8 cm (2.5–3 in), depending on tension and stuffing.</p><h3>Gauge & abbreviations</h3><p>Gauge is less important than making a dense fabric with no obvious stuffing gaps. sc = single crochet · inc = increase (2 sc in one stitch) · dec = decrease · rnd = round · st = stitch.</p><h3>Numbered pattern</h3><ol><li>Rnd 1: 6 sc in a magic ring. (6)</li><li>Rnd 2: inc around. (12)</li><li>Rnd 3: [sc, inc] around. (18)</li><li>Rnd 4: [2 sc, inc] around. (24)</li><li>Rnds 5–8: sc around. (24 each round)</li><li>Rnd 9: [2 sc, dec] around. (18)</li><li>Rnd 10: [sc, dec] around. (12)</li><li>Add stuffing gradually, then Rnd 11: dec around. (6)</li><li>Fasten off, close the opening, and weave the tail through several stitches on the inside.</li></ol><h3>Checkpoint</h3><p>The stitch count should be 6, 12, 18, 24, then 24 for four even rounds, followed by 18, 12 and 6. If it differs, correct the current round before stuffing heavily.</p><h3>Finishing & care</h3><p>Use a firm but flexible fill. For children's items, follow applicable safety guidance and secure embroidered features carefully. Clean according to the yarn label.</p></section>`,
  'crochet-flower': `
    <section class="pattern-card"><h2>Five-petal crochet flower pattern</h2><p><strong>Sample yarn:</strong> cotton #3–4 · <strong>Hook:</strong> 4 mm · <strong>Finished size:</strong> about 6–8 cm (2.5–3 in).</p><h3>Abbreviations</h3><p>ch = chain · sl st = slip stitch · sc = single crochet · dc = double crochet · rep = repeat.</p><h3>Numbered instructions</h3><ol><li>Make a magic ring or ch 4 and join with a sl st.</li><li>Ch 1, then work 10 sc into the center. Join to the first sc.</li><li>For each petal, skip 1 stitch, then work 1 sc, 3 dc, 1 sc in the next stitch. Repeat until five petals are formed.</li><li>Join with a sl st, fasten off and weave the ends securely.</li></ol><h3>Stitch-count checkpoint</h3><p>You should have five visually similar petals. If you get four or six, check the skipped stitch between petals and make sure the center round has the expected 10 sc.</p><h3>Variations</h3><p>Use 4 dc for fuller petals or a smaller hook for a firmer applique. Make one test flower before producing a matching set.</p><h3>Care</h3><p>Shape petals while damp only if the yarn care label permits washing; otherwise gently arrange the flower by hand.</p></section>`,
  'how-to-read-crochet-patterns': `
    <section class="pattern-card"><h2>Pattern-reading practice exercise</h2><p><strong>Sample yarn:</strong> worsted #4 · <strong>Hook:</strong> 5 mm · <strong>Gauge target:</strong> about 15 sc × 16 rows per 10 cm (4 in).</p><h3>Abbreviations</h3><p>ch = chain · sc = single crochet · dc = double crochet · rep = repeat · st = stitch.</p><h3>Numbered exercise</h3><ol><li>Chain 17.</li><li>Sc in the second chain from the hook and across: 16 sc.</li><li>Ch 1, turn. Sc across: 16 sc.</li><li>Repeat the previous row four more times.</li><li>At the end of the sixth row, count 16 stitches before continuing.</li></ol><h3>How to decode the instruction</h3><p>Numbers in parentheses usually report a stitch count, while brackets or asterisks commonly mark a repeat. The pattern's own abbreviation key always wins if it defines a term differently.</p><h3>Troubleshooting</h3><p>If your count is wrong, compare the beginning and end of the row first. If the wording contains a comma or semicolon, separate each action before deciding where the stitches belong.</p><h3>Finishing</h3><p>Write the final stitch count beside each row in pencil or a project note. This simple habit prevents small errors from multiplying.</p></section>`,
  'single-vs-double-crochet': `
    <section class="pattern-card"><h2>Same-yarn stitch comparison swatch</h2><p><strong>Sample yarn:</strong> worsted #4 · <strong>Hook:</strong> 5 mm · <strong>Swatch:</strong> 12 stitches × 8 rows for each stitch.</p><h3>Gauge & finished fabric</h3><p>Measure both sections after they rest flat. Single crochet should create a denser, shorter fabric; double crochet should create a taller fabric with more drape. Your tension may change the exact measurements.</p><h3>Numbered test</h3><ol><li>Chain 13.</li><li>Work 8 rows of sc in the first half, keeping 12 stitches per row.</li><li>Make a second 12-stitch swatch using dc, following the turning-chain instructions of your chosen pattern.</li><li>Measure width and height without stretching.</li><li>Fold, stretch gently and compare density and drape.</li></ol><h3>When to choose each</h3><p>Use sc when you want dense fabric and clear structure. Use dc when you want faster height and more drape. For garments, blankets and bags, choose from the fabric requirement rather than the stitch's popularity.</p><h3>Care</h3><p>Wash the swatch if the finished project will be washed. Fiber and washing can change both gauge and drape.</p></section>`,
  'crochet-hook-sizes-guide': `
    <section class="pattern-card"><h2>Three-hook gauge test</h2><p><strong>Sample yarn:</strong> worsted #4 · <strong>Starting hook:</strong> 5 mm · <strong>Test hooks:</strong> 4.5, 5 and 5.5 mm.</p><h3>Gauge target</h3><p>For a sample project, aim for about 15 sc stitches × 16 rows per 10 cm (4 in). If the pattern specifies a different gauge, use that instead.</p><h3>Numbered test</h3><ol><li>Make three small swatches using the same yarn and stitch.</li><li>Let them relax flat before measuring.</li><li>Count the center 10 cm (4 in), avoiding the edges.</li><li>Compare the fabric with the project's desired density.</li><li>Choose the hook that meets gauge while producing comfortable fabric.</li></ol><h3>Finished-size example</h3><p>If a pattern needs 90 stitches at your target gauge, changing hook size can change the final width even when the stitch count stays 90. That is why gauge should be checked before committing to the full project.</p><h3>Troubleshooting & care</h3><p>If the fabric is stiff, try a larger hook; if it is too loose, try a smaller one. Recheck after washing when the fiber is likely to change size.</p></section>`,
  'how-to-fix-crochet-mistakes': `
    <section class="pattern-card"><h2>Repair practice: find the first wrong stitch</h2><p><strong>Sample yarn:</strong> worsted #4 · <strong>Hook:</strong> 5 mm · <strong>Practice target:</strong> 16 sc per row.</p><h3>Abbreviations</h3><p>sc = single crochet · st = stitch · rep = repeat · frogging = undoing stitches to a previous point.</p><h3>Numbered repair workflow</h3><ol><li>Stop immediately when the shape or stitch count looks wrong.</li><li>Count the current row and write the number down.</li><li>Compare it with the expected count.</li><li>Check the previous row's first and last stitches.</li><li>Look for an increase, decrease or skipped stitch hidden in the middle.</li><li>Undo only to the first incorrect stitch.</li><li>Redo the stitch, then recount the entire row.</li></ol><h3>Example</h3><p>If the pattern calls for 16 sc and you count 15, inspect the final stitch first. If you count 17, check for a turning chain or accidental stitch into a space.</p><h3>Finishing</h3><p>After repairing, gently flatten the fabric and compare both edges. Do not pull hard to hide a count error; tension cannot reliably correct incorrect construction.</p></section>`,
  'crochet-blanket-for-beginners': `
    <section class="pattern-card"><h2>Simple beginner blanket planning example</h2><p><strong>Sample yarn:</strong> worsted #4 · <strong>Hook:</strong> 5 mm · <strong>Example finished size:</strong> 90 × 110 cm (35 × 43 in). Adjust the stitch count to your pattern repeat.</p><h3>Gauge</h3><p>Example target: 15 sc × 16 rows per 10 cm (4 in). Make and wash a swatch before calculating yarn because real fabric can change after washing.</p><h3>Numbered planning steps</h3><ol><li>Decide the finished width and length.</li><li>Measure your washed swatch.</li><li>Multiply stitches per 10 cm by the desired width in 10 cm units.</li><li>Round the result to the nearest valid pattern repeat.</li><li>Make the foundation chain and count it before Row 1.</li><li>After every five rows, check the width and stitch count.</li></ol><h3>Stitch-count checkpoint</h3><p>Keep the same number of stitches in every straight row unless the pattern deliberately increases or decreases. Place markers in the first and last stitch while learning.</p><h3>Finishing & care</h3><p>Weave ends securely, block only if the fiber allows it, and follow the yarn label for washing and drying.</p></section>`,
  'magic-ring-tutorial': `
    <section class="pattern-card"><h2>Magic ring practice pattern</h2><p><strong>Sample yarn:</strong> smooth cotton #3–4 · <strong>Hook:</strong> 4 mm · <strong>Practice result:</strong> a closed center with 6 sc.</p><h3>Abbreviations</h3><p>MR = magic ring · sc = single crochet · sl st = slip stitch · ch = chain · st = stitch.</p><h3>Numbered instructions</h3><ol><li>Form an adjustable loop and leave a 10–15 cm (4–6 in) tail.</li><li>Hold the crossing point securely.</li><li>Chain 1 to anchor the working loop.</li><li>Work 6 sc into the ring, keeping the center open enough for the hook to enter.</li><li>Pull the tail slowly until the center closes.</li><li>Join with a sl st if your project uses joined rounds, or continue directly if it uses continuous rounds.</li></ol><h3>Checkpoint</h3><p>The center should close without forming a hard knot. If it twists, rebuild the ring before adding more rounds.</p><h3>Finishing & care</h3><p>Secure the tail by weaving it through several stitches in different directions. Test the closure gently before trimming. Care follows the yarn label.</p></section>`,
  'crochet-vs-knitting': `
    <section class="pattern-card"><h2>Beginner decision test</h2><p><strong>Sample practice:</strong> smooth worsted #4 yarn. For crochet, try a 5 mm hook; for knitting, use needles appropriate to the yarn label. The exact tool size should follow the fabric you want.</p><h3>Gauge & finished fabric</h3><p>Make a small 10 × 10 cm (4 × 4 in) practice swatch in each craft. Compare density, stretch, drape and how comfortable the fabric feels in your hands.</p><h3>Numbered test</h3><ol><li>Spend 10–15 minutes making a basic crochet swatch.</li><li>Spend the same amount of time making a basic knitted swatch.</li><li>Measure both pieces after they rest flat.</li><li>Try a simple edge and undo one mistake in each.</li><li>Choose the technique you are more motivated to practice.</li></ol><h3>Project fit</h3><p>Crochet can be convenient for structured motifs, amigurumi and one-hook construction. Knitting can be useful when you want a fabric built from many live stitches. Neither craft is universally better.</p><h3>Care</h3><p>Fiber care matters more than the craft name. Keep the yarn label and wash the finished item according to its instructions.</p></section>`,
  'best-yarn-for-amigurumi': `
    <section class="pattern-card"><h2>Amigurumi yarn test</h2><p><strong>Sample yarn:</strong> smooth cotton or cotton-blend #3–4 · <strong>Hook:</strong> 3.5 mm · <strong>Goal:</strong> dense stitches with minimal stuffing visible.</p><h3>Gauge & finished size</h3><p>There is no single universal amigurumi gauge. A useful target is a firm fabric with no obvious holes. A small test ball may finish around 6–8 cm (2.5–3 in), depending on the pattern.</p><h3>Numbered test</h3><ol><li>Make a 6-stitch magic ring.</li><li>Increase to 12 and then 18 stitches over the next two rounds.</li><li>Work several even rounds.</li><li>Add a small amount of stuffing and inspect for gaps.</li><li>Try the same test with another yarn before choosing your main skein.</li></ol><h3>Choosing texture and color</h3><p>Smooth yarn makes stitch counting and embroidered details easier. Fuzzy yarn can create a soft effect but hides stitch definition. Choose color after checking the yarn under the lighting where the finished item will be used.</p><h3>Finishing & care</h3><p>Secure facial details and yarn tails firmly. Follow the fiber's care label and avoid promising machine washing unless the complete finished construction supports it.</p></section>`,
  'how-to-crochet-in-the-round': `
    <section class="pattern-card"><h2>Flat-circle practice pattern</h2><p><strong>Sample yarn:</strong> cotton #3–4 · <strong>Hook:</strong> 4 mm · <strong>Finished size:</strong> about 8–10 cm (3–4 in) after 4 rounds, depending on tension.</p><h3>Abbreviations</h3><p>ch = chain · sc = single crochet · sl st = slip stitch · inc = increase · rnd = round.</p><h3>Numbered pattern</h3><ol><li>Rnd 1: Make a magic ring and work 6 sc into it. (6)</li><li>Rnd 2: Inc in every stitch. (12)</li><li>Rnd 3: [sc, inc] around. (18)</li><li>Rnd 4: [2 sc, inc] around. (24)</li><li>Join with a sl st when using joined rounds, or continue into the next stitch for continuous rounds.</li></ol><h3>Shape checkpoint</h3><p>Lay the circle flat after every round. Cupping usually means the fabric needs more width; strong rippling can mean the increase rate is too high for your yarn and tension. Check the pattern before changing it.</p><h3>Finishing & care</h3><p>Mark the first stitch of each round and record the final count. Wash and dry according to the yarn label.</p></section>`,
  'crochet-stitch-abbreviations': `
    <section class="pattern-card"><h2>Use abbreviations in a real mini pattern</h2><p><strong>Sample yarn:</strong> worsted #4 · <strong>Hook:</strong> 5 mm · <strong>Gauge target:</strong> about 15 sc × 16 rows per 10 cm (4 in).</p><h3>Core abbreviations</h3><p>ch = chain · sc = single crochet · hdc = half double crochet · dc = double crochet · sl st = slip stitch · inc = increase · dec = decrease · rep = repeat · rnd = round · st = stitch.</p><h3>Numbered practice</h3><ol><li>Ch 17.</li><li>Sc in the 2nd ch from hook and across. (16 sc)</li><li>Ch 1, turn; sc across. (16 sc)</li><li>Rep Row 3 four times.</li><li>Fasten off and weave the end.</li></ol><h3>How to verify a pattern</h3><p>Read the abbreviation key first. Then identify the action, location, repeat and expected stitch count. A stitch count is one of the best checkpoints you have.</p><h3>Troubleshooting & finishing</h3><p>If a symbol or abbreviation conflicts with your pattern's own glossary, follow that pattern's definition. Keep a written note of unfamiliar terms and weave the final ends securely.</p></section>`
}

const style = `<style>.pattern-card{margin:34px 0;padding:26px;border:1px solid rgba(25,48,43,.14);background:#fbfaf6}.pattern-card h2{margin-top:0}.pattern-card h3{margin-top:22px}.pattern-card ol{padding-left:24px}.pattern-card li{margin:8px 0}.pattern-card p{line-height:1.75}</style>`

const plugin = {
  name: 'crochet-seo-content-upgrade',
  transformIndexHtml(html, ctx) {
    const path = ctx.path || ''
    if (!path.includes('/posts/')) return html
    const slug = path.split('/posts/')[1]?.replace(/\.html$/, '') || ''
    const content = upgrades[slug]
    if (!content || html.includes('class="pattern-card"')) return html
    return html.replace('</article>', `${content}</article>`).replace('</head>', `${style}</head>`)
  }
}

export default plugin
